version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 1
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      all-others:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 1
    groups:
      all-others:
        patterns:
          - "*"
